### ISSUE TITLE
ThinkServer?

### ISSUE THREAD

**Issue by sqpp** [roadkell/ascii-art-logos#3]
Hello,

Could you possibly create a ThinkServer version of the vertical?

**Comment by roadkell** [comment]
Hello and thanks for the idea, I'll do it around tomorrow or so. )

**Comment by roadkell** [comment]
Done. Sorry for the delay. I wasn't really satisfied with the result and planned to work a bit more on it, but alas, no spare time yet.

**Comment by sqpp** [comment]
Thank you so much :)
